---
- name: Install la base from los equipos de los laboratorios de Greencore Solutions
  hosts: all
  environment:
    - ARCH: arm
    - OLD_PWD: "{{ ansible_user }}/nexmon"
    - SUBARCH: arm
    - KERNEL: kernel7
    - HOSTUNAME: Linux
    - PLATFORMUNAME: armv7l
    - CC: /home/pi/nexmon/buildtools/gcc-arm-none-eabi-5_4-2016q2-linux-armv7l/bin/arm-none-eabi-
    - CCPLUGIN: /home/pi/nexmon/buildtools/gcc-nexmon-plugin-arm/nexmon.so
    - ZLIBFLATE: zlib-flate -compress
    - NEXMON_ROOT: /home/pi/nexmon
    - NEXMON_SETUP_ENV: 1
  roles:
    # - common
    - nexmon

  